---  
- name: Deploy HAPI FHIR
  get_url: url=https://www.dropbox.com/s/ke6qi40zvm7yrhc/hapi-fhir-jpaserver-example.war?dl=1 dest=/tmp/hapi-fhir-jpaserver-example.war force=no

- name: Assure database dir
  file: path=/usr/share/tomcat/derby state=directory owner=tomcat group=tomcat
  sudo: yes

- name: Change ownership & copy
  shell: chown tomcat.tomcat /tmp/hapi-fhir-jpaserver-example.war
  shell: cp /tmp/hapi-fhir-jpaserver-example.war /usr/share/tomcat/webapps/fhir.war
  sudo: yes
