---  
- name: Deploy HAPI FHIR
  get_url: url=https://www.dropbox.com/s/ke6qi40zvm7yrhc/hapi-fhir-jpaserver-example.war?dl=1 dest=/tmp/hapi-fhir-jpaserver-example.war force=no

- name: Assure database dir
  file: path=/usr/share/tomcat/derby state=directory owner=tomcat group=tomcat
  sudo: yes

- name: Change ownership & copy
  file: path=/tmp/hapi-fhir-jpaserver-example.war owner=tomcat group=tomcat
  sudo: yes

- shell: cp -n /tmp/hapi-fhir-jpaserver-example.war /usr/share/tomcat/webapps/fhir.war
  sudo: yes

- name: wait app to (re)-start
  pause: seconds=30

- name: copy valueset 
  copy: src=valueSets.json dest=/tmp/valueSets.json

- name: push valuesets to FHIR
  shell: curl -vv -X POST -H 'Content-type:application/json' --data '@/tmp/valueSets.json' http://127.0.0.1:{{http_port}}/fhir/baseDstu2
