---
- name: create user for DRE components
  user: name=dre group=users
  
- name: install parsers
  git: repo=https://github.com/amida-tech/dre-parsers.git dest=/home/dre/dre-parsers update=yes
  sudo: yes
  sudo_user: dre
   
- name: build parsers (1)
  npm: path=/home/dre/dre-parsers
  sudo: yes
  sudo_user: dre

#- name: build parsers (2)
#  shell: grunt chdir=/home/dre/dre-parsers
#  sudo: yes
#  sudo_user: dre
  
- name: Install DRE parsers service config
  template: src=dre-parsers.service dest=/etc/systemd/system/dre-parsers.service
  notify: restart dre-parsers

- name: restart dre-parsers 
  service: name=dre-parsers enabled=yes state=started

